### ISSUE TITLE
[Bug] Cannot start the app after checking it out of GitHub 

### ISSUE THREAD

**Issue by parik-ceb** [creativetimofficial/argon-design-system-react#18] opened 2020-07-12 21:45 UTC
### Version
[1.1.0] 2020-02-14
### Reproduction link
https://github.com/creativetimofficial/argon-design-system-react
### Operating System
macOS Catalina 10.15.5 (19F101)
### Device
iMac
### Browser & Version
Chrome Version 83.0.4103.116 (Official Build) (64-bit)
### Steps to reproduce
1. Git clone the repo
2. npm i 
3. npm start
4. open localhost:3000 in chrome
### What is expected?
The default landing page should be displayed.
### What is actually happening?
The following error is displayed on the page: 

```TypeError [ERR_INVALID_ARG_TYPE]: The “path” argument must be of type string. Received type undefined raised when starting react app```

---
### Solution
I was able to resolve the issue by updating the version of react-scripts.
Updating the version from 
```"react-scripts": "3.3.1",```
to
```"react-scripts": "3.4.1", ```

 Solution details are mentioned here -> https://stackoverflow.com/questions/60234640/typeerror-err-invalid-arg-type-the-path-argument-must-be-of-type-string-re
### Additional comments
Hope this helps other developers who are planning to use your template. This template has been a big help for me!!!

**Comment by rjhilgefort** [comment] 2020-07-16 03:42
Yeah, I'm seeing this as well after a fresh clone 🙁

**Comment by einazare** [comment] 2020-07-16 06:23
@rjhilgefort , in the above comment, you have a solution stated there. We'll update this product in 4 months and the issue will be solved then. Also, if you wish to have the latest improvements over this product, you can download the dev-master branch: https://github.com/creativetimofficial/argon-design-system-react/tree/dev-master

**Comment by rjhilgefort** [comment] 2020-07-16 14:13
@EINazare Yep, I put that solution in place but just thought I'd chime in to let you know that it's not isolated to one user. Cheers!

**Comment by jessicakuijer** [comment] 2020-08-11 11:24
> @rjhilgefort , in the above comment, you have a solution stated there. We'll update this product in 4 months and the issue will be solved then. Also, if you wish to have the latest improvements over this product, you can download the dev-master branch: https://github.com/creativetimofficial/argon-design-system-react/tree/dev-master

this totally works!!! thanks for bringing up that branch!!!!

**Comment by aXb0t** [comment] 2021-02-28 16:08
Hello - just running this demo design system theme today, and can report the same issue as of today, for any future developers who find this.

The error message reads as above, and the solution also reads as above:

Update `package.json` to  `"react-scripts": "3.4.1"` and then run `npm run install:clean`

Thank you, this Issue report was very helpful and the design system looks great!

**Comment by sajadevo** [comment] 2022-08-26 06:39
Hi there,

The issue is fixed on the latest version of the product.

Regards,
Sajad

**Closed as completed by sajadevo** 2022-08-26 06:39 UTC
Labels: bug
